name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install deps and prepare
        uses: cypress-io/github-action@v5.1.0
        with:
          browser: replay-chromium
          build: npm run build
          start: npm run dev
          runTests: false

      - name: Run tests
        uses: cypress-io/github-action@v5.1.0
        with:
          working-directory: ./packages/site
          install: false


      # Always run this step so failed tests are uploaded
      - name: Upload replays
        if: always()
        uses: replayio/action-upload@v0.4.7
        with:
          api-key: ${{ secrets.RECORD_REPLAY_API_KEY }}